id = "kilo"
name = "Kilo"
description = "The open source coding agent."
version = "1.0.25"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/Kilo-Org/kilocode"

[agent_servers.opencode]
name = "Kilo"
icon = "./icons/opencode.svg"

[agent_servers.opencode.targets.darwin-aarch64]
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v1.0.25/kilo-darwin-arm64.zip"
cmd = "./kilo"
args = ["acp"]

[agent_servers.opencode.targets.darwin-x86_64]
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v1.0.25/kilo-darwin-x64.zip"
cmd = "./kilo"
args = ["acp"]

[agent_servers.opencode.targets.linux-aarch64]
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v1.0.25/kilo-linux-arm64.tar.gz"
cmd = "./kilo"
args = ["acp"]

[agent_servers.opencode.targets.linux-x86_64]
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v1.0.25/kilo-linux-x64.tar.gz"
cmd = "./kilo"
args = ["acp"]

[agent_servers.opencode.targets.windows-x86_64]
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v1.0.25/kilo-windows-x64.zip"
cmd = "./kilo.exe"
args = ["acp"]
